server:
  port : 8081

spring:
  profiles:
    active: dev
  application:
    name: gateway-service

zuul:
  host:
    socket-timeout-millis: 30000
  routes:
    schedule-route:
      url: http://localhost:8083
      path: /schedule/**
    course-route:
      url: http://localhost:8084
      path: /lecture/**

